[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyadtpulse"
version="1.1.1"
description="Python interface for ADT Pulse security systems"
readme="README.md"
author="Ryan Snodgrass"
maintainer="Robert Lippmann"
url="https://github.com/rsnodgrass/pyadtpulse"
license="Apache Software License"
install_requires=["aiohttp>=3.8.1", "uvloop>=0.17.0", "bs4>=4.11.1", "python_dateutil>=2.8.2"]
keywords=["security system", "adt", "home automation", "security alarm"]
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ]

[project.urls]
"Changelog" = "https://github.com/rsnodgrass/pyadtpulse/blob/master/CHANGELOG.md"
"Source" = "https://github.com/rsnodgrass/pyadtpulse"

[tool.isort]
profile = "black"
force_to_top = [ "logging" ]
balanced_wrapping = true

[black]
line-length = 90

[tool.pycln]
all = true
