name: Bandit
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          config-file: pyproject.toml
