name: Bandit
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Run Bandit
        run: |
          uv run bandit --configfile pyproject.toml -r .
